name: Build and Push Docker Image ios

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Expo Prebuild
        run: npx expo prebuild


      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace "cicd.xcworkspace" -scheme cicd -configuration Release -sdk iphoneos -archivePath $PWD/build/cicd.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO archive
          xcodebuild -exportArchive -archivePath $PWD/build/cicd.xcarchive -exportPath $PWD/build/ -exportOptionsPlist $PWD/Info.plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicd.ipa
          path: ios/build/cicd.ipa

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ios_docker
          file: ios_docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reactnative:unsigned_ios_no_cache_fixed

      - name: Logout from Docker Hub
        run: docker logout
