name: Build and Push Docker Image ios

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Yarn
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Expo Prebuild
        run: npx expo prebuild --platform ios --no-install

      - name: Cache CocoaPods
        id: pod-cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ios/Podfile.lock
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Install CocoaPods dependencies
        if: steps.pod-cache.outputs.cache-hit != 'true'
        run: |
          cd ios
          pod install

      - name: Create ExportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ios/cicd/ExportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ios/cicd/ExportOptions.plist
          echo '<plist version="1.0">' >> ios/cicd/ExportOptions.plist
          echo '<dict>' >> ios/cicd/ExportOptions.plist
          echo '  <key>method</key>' >> ios/cicd/ExportOptions.plist
          echo '  <string>ad-hoc</string>' >> ios/cicd/ExportOptions.plist
          echo '  <key>signingStyle</key>' >> ios/cicd/ExportOptions.plist
          echo '  <string>manual</string>' >> ios/cicd/ExportOptions.plist
          echo '  <key>teamID</key>' >> ios/cicd/ExportOptions.plist
          echo '  <string>TTTTTTTT00</string>' >> ios/cicd/ExportOptions.plist
          echo '  <key>provisioningProfiles</key>' >> ios/cicd/ExportOptions.plist
          echo '  <dict>' >> ios/cicd/ExportOptions.plist
          echo '    <key>com.overlordrr.cicd</key>' >> ios/cicd/ExportOptions.plist
          echo '    <string></string>' >> ios/cicd/ExportOptions.plist
          echo '  </dict>' >> ios/cicd/ExportOptions.plist
          echo '</dict>' >> ios/cicd/ExportOptions.plist
          echo '</plist>' >> ios/cicd/ExportOptions.plist
      - name: Build iOS app
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        run: |
          cd ios
          xcodebuild -workspace "cicd.xcworkspace" \
            -scheme cicd \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/cicd.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
          
          xcodebuild -exportArchive \
            -archivePath $PWD/build/cicd.xcarchive \
            -exportPath $PWD/build/ \
            -exportOptionsPlist $PWD/cicd/ExportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicd.ipa
          path: ios/build/cicd.ipa

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ios_docker
          file: ios_docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reactnative:unsigned_ios_no_cache_fixed

      - name: Logout from Docker Hub
        run: docker logout
